### ISSUE TITLE
lint-readme: insert semicolons more discerningly

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary-scripts#14]
The script (see below) that rewrites code blocks for linting should be smarter about inserting semicolons, so that the linter will not complain about misplaced semicolons.

https://github.com/sanctuary-js/sanctuary-scripts/blob/ce8733dbb2ab7da12e7418559e7b3030886d24f8/bin/lint-readme#L16-L41

See https://github.com/Avaq/permissionary/pull/5 for discussion leading up to this.

**Comment by gabejohnson** [comment]
Why do we have a script to rewrite code blocks? Is this to work around limitations of ESLint?

**Comment by Avaq** [comment]
@gabejohnson Because codeblocks are written for https://github.com/davidchambers/doctest with additional information prefixed to every line in the form of `>`, `.`, and `!` characters.

**Comment by gabejohnson** [comment]
Ahhh..._those_ code blocks. Thanks for the explanation Aldwin 😄
